name : Output Information
on : 
   pull_request :
    types :
        - closed
jobs :
    githubinfos :
        runs-on : ubuntu-latest
        steps :
            - name : Output Github Context
              run : echo "${{ toJSON(github)}}"
