name : Output Information
on : 
   pull_request :
    types :
        - closed
jobs : 
    githubinfo : #provide a name to your job
        runs-on : ubuntu-latest  # select a machine to run
        steps :  #adde the next steps
            - name : Output Github Context  #provide a name to the step
              run : echo "${{ toJSON(github)}}" #provide a action what to so
